#10 worker
data_10 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/10/res_u.csv")
data_10_memAct <- aggregate(mem_act~size,data_10,mean)
data_10_memTrans <- aggregate(mem_trans~size,data_10,mean)
data_10_cpuUser <- aggregate(cpu_user~size,data_10,mean)
data_10_cpuSyst <- aggregate(cpu_system~size,data_10,mean)
data_10_byteIn <- aggregate(bytes_in~size,data_10,mean)
data_10_byteOut <- aggregate(bytes_out~size,data_10,mean)
data_10_status <- aggregate(status~size,data_10,mean)
#9 worker
data_9 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/9/res_u.csv")
data_9_memAct <- aggregate(mem_act~size,data_9,mean)
data_9_memTrans <- aggregate(mem_trans~size,data_9,mean)
data_9_cpuUser <- aggregate(cpu_user~size,data_9,mean)
data_9_cpuSyst <- aggregate(cpu_system~size,data_9,mean)
data_9_byteIn <- aggregate(bytes_in~size,data_9,mean)
data_9_byteOut <- aggregate(bytes_out~size,data_9,mean)
data_9_status <- aggregate(status~size,data_9,mean)
#8 worker
data_8 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/8/res_u.csv")
data_8_memAct <- aggregate(mem_act~size,data_8,mean)
data_8_memTrans <- aggregate(mem_trans~size,data_8,mean)
data_8_cpuUser <- aggregate(cpu_user~size,data_8,mean)
data_8_cpuSyst <- aggregate(cpu_system~size,data_8,mean)
data_8_byteIn <- aggregate(bytes_in~size,data_8,mean)
data_8_byteOut <- aggregate(bytes_out~size,data_8,mean)
data_8_status <- aggregate(status~size,data_8,mean)
#7 worker
data_7 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/7/res_u.csv")
data_7_memAct <- aggregate(mem_act~size,data_7,mean)
data_7_memTrans <- aggregate(mem_trans~size,data_7,mean)
data_7_cpuUser <- aggregate(cpu_user~size,data_7,mean)
data_7_cpuSyst <- aggregate(cpu_system~size,data_7,mean)
data_7_byteIn <- aggregate(bytes_in~size,data_7,mean)
data_7_byteOut <- aggregate(bytes_out~size,data_7,mean)
data_7_status <- aggregate(status~size,data_7,mean)
#6 worker
data_6 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/6/res_u.csv")
data_6_memAct <- aggregate(mem_act~size,data_6,mean)
data_6_memTrans <- aggregate(mem_trans~size,data_6,mean)
data_6_cpuUser <- aggregate(cpu_user~size,data_6,mean)
data_6_cpuSyst <- aggregate(cpu_system~size,data_6,mean)
data_6_byteIn <- aggregate(bytes_in~size,data_6,mean)
data_6_byteOut <- aggregate(bytes_out~size,data_6,mean)
data_6_status <- aggregate(status~size,data_6,mean)
#5 worker
data_5 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/5/res_u.csv")
data_5_memAct <- aggregate(mem_act~size,data_5,mean)
data_5_memTrans <- aggregate(mem_trans~size,data_5,mean)
data_5_cpuUser <- aggregate(cpu_user~size,data_5,mean)
data_5_cpuSyst <- aggregate(cpu_system~size,data_5,mean)
data_5_byteIn <- aggregate(bytes_in~size,data_5,mean)
data_5_byteOut <- aggregate(bytes_out~size,data_5,mean)
data_5_status <- aggregate(status~size,data_5,mean)
#4 worker
data_4 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/4/res_u.csv")
data_4_memAct <- aggregate(mem_act~size,data_4,mean)
data_4_memTrans <- aggregate(mem_trans~size,data_4,mean)
data_4_cpuUser <- aggregate(cpu_user~size,data_4,mean)
data_4_cpuSyst <- aggregate(cpu_system~size,data_4,mean)
data_4_byteIn <- aggregate(bytes_in~size,data_4,mean)
data_4_byteOut <- aggregate(bytes_out~size,data_4,mean)
data_4_status <- aggregate(status~size,data_4,mean)
#3 worker
data_3 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/3/res_u.csv")
data_3_memAct <- aggregate(mem_act~size,data_3,mean)
data_3_memTrans <- aggregate(mem_trans~size,data_3,mean)
data_3_cpuUser <- aggregate(cpu_user~size,data_3,mean)
data_3_cpuSyst <- aggregate(cpu_system~size,data_3,mean)
data_3_byteIn <- aggregate(bytes_in~size,data_3,mean)
data_3_byteOut <- aggregate(bytes_out~size,data_3,mean)
data_3_status <- aggregate(status~size,data_3,mean)
#2 worker
data_2 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/2/res_u.csv")
data_2_memAct <- aggregate(mem_act~size,data_2,mean)
data_2_memTrans <- aggregate(mem_trans~size,data_2,mean)
data_2_cpuUser <- aggregate(cpu_user~size,data_2,mean)
data_2_cpuSyst <- aggregate(cpu_system~size,data_2,mean)
data_2_byteIn <- aggregate(bytes_in~size,data_2,mean)
data_2_byteOut <- aggregate(bytes_out~size,data_2,mean)
data_2_status <- aggregate(status~size,data_2,mean)
#1 worker
data_1 <- read.csv("~/Desktop/analyse_nectecPaperRes/src/1/res_u.csv")
data_1_memAct <- aggregate(mem_act~size,data_1,mean)
data_1_memTrans <- aggregate(mem_trans~size,data_1,mean)
data_1_cpuUser <- aggregate(cpu_user~size,data_1,mean)
data_1_cpuSyst <- aggregate(cpu_system~size,data_1,mean)
data_1_byteIn <- aggregate(bytes_in~size,data_1,mean)
data_1_byteOut <- aggregate(bytes_out~size,data_1,mean)
data_1_status <- aggregate(status~size,data_1,mean)